
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"  # Para ver con VNC si quieres

  test-runner:
    build:
      context: ./test
    depends_on:
      - selenium
    volumes:
      - ./output:/tmp
