version: '3'
services:
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium-chrome2
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 2gb

  tester:
    build: .
    depends_on:
      - selenium
    volumes:
      - ./output:/app/output
